<div data-bind="scope: 'dan-component'">
  <h2 data-bind="text: title"></h2>
</div>


<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
              "components":{
                "dan-component": {
                  "component":"Dan_Practice/js/component",
                  "title":"Hello Dan"
                }
              }
            }
        }
    }
</script>
